### ISSUE TITLE
where is get_best_pickle.py

### ISSUE THREAD

**Issue by cheryyunl** [huanzhang12/ATLA_robust_RL#1]
Hi, when I want to extract my best adversary model, why:
python: can't open file 'get_best_pickle.py': [Errno 2] No such file or directory

**Comment by huanzhang12** [comment]
Hi @Chersophyte, you can find the `get_best_pickle.py` under the src folder: https://github.com/huanzhang12/ATLA_robust_RL/blob/main/src/get_best_pickle.py

**Comment by cheryyunl** [comment]
Thank you so much!!!
